runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: 2.7
- name: numpy
  version: "latest"
- name: matplotlib
  version: "latest"

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'anyvalue'

handlers:
- url: /travel.*
  script: timeplot.app
- url: /arrive.*
  script: timeplot.app
- url: /plot.*
  script: timeplot.app
- url: /pmplot
  script: timeplot.app
- url: /plot
  script: timeplot.app
- url: /collectdata
  script: collector.app
- url: /whentogo
  script: whentogo.app
- url: /.*
  script: timeplot.app

