runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: 2.7

handlers:
- url: /collectdata
  script: collector.app
- url: /whentogo
  script: whentogo.app
- url: /.*
  script: main.app

